version: "3.5"

services:
  backend-server:
    build: Backend/
    container_name: taskData
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - database
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: database
      MYSQL_DATABASE: TaskData
      PORT: '3000'

  database:
    container_name: taskDatabase
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./Database/data.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3001:3306

networks:
  default:
    name: default_database
